//! Native `generate_image` tool: OpenAI-compatible image generation
//! (`POST {base}/images/generations`), with first-class support for xAI's
//! Imagine API (`grok-imagine-image` / `grok-imagine-image-quality`).
//!
//! Auth prefers the active provider when it is xAI / OpenAI / OpenRouter,
//! then falls back to the xAI OAuth session / stored key / `XAI_API_KEY`
//! (same pattern as xAI web search). Generated bytes always land on disk so
//! the agent can open a local path.

use std::path::{Path, PathBuf};
use std::time::Duration;

use async_trait::async_trait;
use base64::Engine;
use base64::engine::general_purpose::STANDARD as BASE64;
use serde::Deserialize;
use serde_json::{Value, json};

use super::{Tool, ToolAccess, ToolContext, ToolError, ToolOutput, parse_args, resolve_path};
use crate::config::{Config, ProviderKind};
use crate::llm::openai::TokenSource;
use crate::llm::xai_oauth::{self, XaiTokenSource};

/// Whole-request timeout for image generation (model work is slower than chat).
const GENERATE_TIMEOUT: Duration = Duration::from_secs(180);

/// Cap on a single downloaded / decoded image body (20 MiB).
const MAX_IMAGE_BYTES: usize = 20 * 1024 * 1024;

/// Default xAI Imagine model (higher quality).
const DEFAULT_XAI_MODEL: &str = "grok-imagine-image-quality";

/// Sensible default when talking to OpenAI's images API.
const DEFAULT_OPENAI_MODEL: &str = "dall-e-3";

/// Max images per call (API and disk safety).
const MAX_N: u32 = 4;

/// How `generate_image` authenticates.
enum ImageAuth {
    Oauth(XaiTokenSource),
    ApiKey(String),
}

/// Resolved endpoint + credentials for one generation call.
struct ImageEndpoint {
    base_url: String,
    /// Whether the base URL is an xAI host (drives default model choice).
    is_xai: bool,
    auth: ImageAuth,
}

impl ImageEndpoint {
    async fn bearer(&self) -> anyhow::Result<String> {
        match &self.auth {
            ImageAuth::ApiKey(key) => Ok(key.clone()),
            ImageAuth::Oauth(source) => source
                .bearer()
                .await?
                .ok_or_else(|| anyhow::anyhow!("no xAI OAuth token available; run `/login xai`")),
        }
    }

    async fn refresh_after_unauthorized(&self) -> bool {
        match &self.auth {
            ImageAuth::Oauth(source) => source.refresh_after_unauthorized().await.unwrap_or(false),
            ImageAuth::ApiKey(_) => false,
        }
    }
}

/// Arguments for [`GenerateImageTool`].
#[derive(Debug, Deserialize)]
struct GenerateImageArgs {
    /// Image description.
    prompt: String,
    /// Where to save (relative to project root or absolute). Default:
    /// `generated/<timestamp>-<slug>.png`.
    #[serde(default)]
    path: Option<String>,
    /// Image model. Defaults depend on the endpoint (xAI Imagine quality, or
    /// `dall-e-3` for OpenAI).
    #[serde(default)]
    model: Option<String>,
    /// Number of images (1–4, default 1).
    #[serde(default)]
    n: Option<u32>,
    /// Aspect ratio (xAI Imagine), e.g. `1:1`, `16:9`, `9:16`.
    #[serde(default)]
    aspect_ratio: Option<String>,
    /// Resolution (xAI Imagine): `1k` or `2k`.
    #[serde(default)]
    resolution: Option<String>,
    /// `url` (default; download to file) or `b64_json` (decode to file).
    #[serde(default)]
    response_format: Option<String>,
}

/// One image payload from an OpenAI-compatible generations response.
#[derive(Debug, Clone, PartialEq, Eq)]
pub(crate) struct GeneratedImage {
    pub url: Option<String>,
    pub b64_json: Option<String>,
}

/// `generate_image` — call an OpenAI-compatible images endpoint and write the
/// result to a local file.
pub struct GenerateImageTool;

#[async_trait]
impl Tool for GenerateImageTool {
    fn name(&self) -> &str {
        "generate_image"
    }

    fn description(&self) -> &str {
        "Generate an image from a text prompt via xAI Imagine (or any OpenAI-compatible \
         images endpoint). Saves the result under generated/ (or a path you pass) and \
         returns the local file path."
    }

    fn parameters(&self) -> Value {
        json!({
            "type": "object",
            "properties": {
                "prompt": {
                    "type": "string",
                    "description": "Image description"
                },
                "path": {
                    "type": "string",
                    "description": "Where to save (relative to project root or absolute). \
                                    Default: generated/<timestamp>-<slug>.png under the project root"
                },
                "model": {
                    "type": "string",
                    "description": "Image model (default grok-imagine-image-quality on xAI, \
                                    dall-e-3 on OpenAI)"
                },
                "n": {
                    "type": "integer",
                    "description": "Number of images (1–4, default 1)"
                },
                "aspect_ratio": {
                    "type": "string",
                    "description": "Aspect ratio for xAI Imagine (e.g. 1:1, 16:9, 9:16, 4:3)"
                },
                "resolution": {
                    "type": "string",
                    "description": "Resolution for xAI Imagine: 1k or 2k"
                },
                "response_format": {
                    "type": "string",
                    "description": "url (default; download to file) or b64_json"
                }
            },
            "required": ["prompt"]
        })
    }

    fn access(&self) -> ToolAccess {
        ToolAccess::Execute
    }

    async fn execute(&self, args: Value, ctx: &ToolContext) -> Result<ToolOutput, ToolError> {
        let args: GenerateImageArgs = parse_args(self.name(), args)?;
        if args.prompt.trim().is_empty() {
            return Err(ToolError::InvalidArgs {
                tool: self.name().to_string(),
                message: "prompt must not be empty".to_string(),
            });
        }
        let n = args.n.unwrap_or(1);
        if n == 0 || n > MAX_N {
            return Err(ToolError::InvalidArgs {
                tool: self.name().to_string(),
                message: format!("n must be between 1 and {MAX_N}"),
            });
        }
        if let Some(format) = args.response_format.as_deref() {
            let format = format.trim().to_ascii_lowercase();
            if format != "url" && format != "b64_json" {
                return Err(ToolError::InvalidArgs {
                    tool: self.name().to_string(),
                    message: "response_format must be \"url\" or \"b64_json\"".to_string(),
                });
            }
        }
        if let Some(resolution) = args.resolution.as_deref() {
            let resolution = resolution.trim().to_ascii_lowercase();
            if resolution != "1k" && resolution != "2k" {
                return Err(ToolError::InvalidArgs {
                    tool: self.name().to_string(),
                    message: "resolution must be \"1k\" or \"2k\"".to_string(),
                });
            }
        }

        let endpoint = match resolve_endpoint() {
            Ok(endpoint) => endpoint,
            Err(reason) => return Ok(ToolOutput::error(reason)),
        };

        let model = args
            .model
            .as_deref()
            .map(str::trim)
            .filter(|m| !m.is_empty())
            .map(str::to_string)
            .unwrap_or_else(|| default_model(endpoint.is_xai));

        let response_format = args
            .response_format
            .as_deref()
            .map(str::trim)
            .filter(|s| !s.is_empty())
            .unwrap_or("url");

        let body = build_request_body(
            &model,
            args.prompt.trim(),
            n,
            args.aspect_ratio.as_deref(),
            args.resolution.as_deref(),
            response_format,
        );

        let client = match reqwest::Client::builder()
            .timeout(GENERATE_TIMEOUT)
            .connect_timeout(Duration::from_secs(15))
            .build()
        {
            Ok(client) => client,
            Err(err) => {
                return Ok(ToolOutput::error(format!(
                    "failed to build HTTP client: {err}"
                )));
            }
        };

        let url = format!(
            "{}/images/generations",
            endpoint.base_url.trim_end_matches('/')
        );

        let response = match post_generations(&client, &url, &endpoint, &body).await {
            Ok(response) => response,
            Err(err) => {
                return Ok(ToolOutput::error(format!(
                    "image generation failed: {err:#}"
                )));
            }
        };

        let payload: Value = match response.json().await {
            Ok(payload) => payload,
            Err(err) => {
                return Ok(ToolOutput::error(format!(
                    "failed to parse image generation response: {err}"
                )));
            }
        };
        if let Some(message) = payload["error"]["message"].as_str() {
            return Ok(ToolOutput::error(format!(
                "image generation error: {message}"
            )));
        }

        let images = match parse_generations_response(&payload) {
            Ok(images) if !images.is_empty() => images,
            Ok(_) => {
                return Ok(ToolOutput::error(
                    "image generation returned no images".to_string(),
                ));
            }
            Err(err) => return Ok(ToolOutput::error(err)),
        };

        let base_path = match args.path.as_deref() {
            Some(path) if !path.trim().is_empty() => resolve_path(ctx, path.trim()),
            _ => default_output_path(&ctx.cwd, args.prompt.trim()),
        };

        let mut lines = Vec::new();
        let mut generated: Vec<crate::llm::Image> = Vec::new();
        for (index, image) in images.iter().enumerate() {
            let path = output_path_for_index(&base_path, index, images.len());
            let (bytes, source_url) = match materialize_image(&client, image).await {
                Ok(result) => result,
                Err(err) => {
                    return Ok(ToolOutput::error(format!(
                        "failed to obtain image #{}: {err:#}",
                        index + 1
                    )));
                }
            };
            if let Err(err) = write_image_file(&path, &bytes).await {
                return Ok(ToolOutput::error(format!(
                    "failed to write {}: {err}",
                    path.display()
                )));
            }
            let mut line = format!("- {}", path.display());
            if let Some(url) = source_url {
                line.push_str(&format!("\n  (url: {url})"));
            }
            // The image travels with the result, not just its path: the agent
            // loop writes it to the session's image store, shows it inline in
            // the GUI and TUI, and hands it back to the model, which can then
            // see what it asked for. A payload the carry cap refuses (or a
            // format we cannot name) is still on disk and still named here —
            // it just does not ride along.
            match crate::llm::Image::from_bytes(&bytes) {
                Ok(image) => generated.push(image),
                Err(err) => {
                    tracing::warn!("{} is not carried inline: {err}", path.display());
                    line.push_str(&format!("\n  (not shown inline: {err})"));
                }
            }
            lines.push(line);
        }

        Ok(ToolOutput::ok_with_images(
            format!("generated {} image(s):\n{}", lines.len(), lines.join("\n")),
            generated,
        ))
    }
}

/// Prefer the active provider when it can serve images; otherwise fall back to
/// xAI OAuth / credentials / `XAI_API_KEY`.
fn resolve_endpoint() -> Result<ImageEndpoint, String> {
    if let Ok(config) = Config::load() {
        let provider = config.active();
        match provider.kind {
            ProviderKind::XaiOauth => {
                if xai_signed_in() {
                    let source = XaiTokenSource::new()
                        .map_err(|err| format!("opening the xAI OAuth token store: {err:#}"))?;
                    return Ok(ImageEndpoint {
                        base_url: provider.base_url,
                        is_xai: true,
                        auth: ImageAuth::Oauth(source),
                    });
                }
                // Active is OAuth but no session — try key fallbacks below with
                // this provider's base URL first if a key exists.
                if let Some(endpoint) = api_key_endpoint(
                    &provider.base_url,
                    true,
                    Some(xai_oauth::DEFAULT_KEY_ENV),
                    &["xai", &provider.name],
                ) {
                    return Ok(endpoint);
                }
            }
            ProviderKind::Xai => {
                if let Some(endpoint) = api_key_endpoint(
                    &provider.base_url,
                    true,
                    provider
                        .api_key_env
                        .as_deref()
                        .or(Some(xai_oauth::DEFAULT_KEY_ENV)),
                    &["xai", &provider.name],
                ) {
                    return Ok(endpoint);
                }
            }
            ProviderKind::Openai | ProviderKind::OpenRouter => {
                let default_env = match provider.kind {
                    ProviderKind::OpenRouter => Some(crate::llm::openrouter::DEFAULT_KEY_ENV),
                    _ => Some("OPENAI_API_KEY"),
                };
                if let Some(endpoint) = api_key_endpoint(
                    &provider.base_url,
                    is_xai_base_url(&provider.base_url),
                    provider.api_key_env.as_deref().or(default_env),
                    &[&provider.name],
                ) {
                    return Ok(endpoint);
                }
            }
            _ => {}
        }
    }

    // Fallback: xAI OAuth session, then stored/env key for xAI.
    if xai_signed_in() {
        let source = XaiTokenSource::new()
            .map_err(|err| format!("opening the xAI OAuth token store: {err:#}"))?;
        return Ok(ImageEndpoint {
            base_url: xai_oauth::DEFAULT_BASE_URL.to_string(),
            is_xai: true,
            auth: ImageAuth::Oauth(source),
        });
    }
    if let Some(endpoint) = api_key_endpoint(
        xai_oauth::DEFAULT_BASE_URL,
        true,
        Some(xai_oauth::DEFAULT_KEY_ENV),
        &["xai"],
    ) {
        return Ok(endpoint);
    }

    Err(
        "image generation needs auth: run `/login xai` to sign in, set XAI_API_KEY \
         (or an OpenAI/OpenRouter key when that provider is active), or store a key \
         via /provider"
            .to_string(),
    )
}

/// Build an API-key endpoint when a non-empty key is available under any of
/// `credential_names` or the named env var.
fn api_key_endpoint(
    base_url: &str,
    is_xai: bool,
    env_name: Option<&str>,
    credential_names: &[&str],
) -> Option<ImageEndpoint> {
    for name in credential_names {
        if let Some(key) = crate::credentials::get(name)
            && !key.trim().is_empty()
        {
            return Some(ImageEndpoint {
                base_url: base_url.to_string(),
                is_xai,
                auth: ImageAuth::ApiKey(key),
            });
        }
    }
    if let Some(env_name) = env_name
        && let Ok(key) = std::env::var(env_name)
        && !key.trim().is_empty()
    {
        return Some(ImageEndpoint {
            base_url: base_url.to_string(),
            is_xai,
            auth: ImageAuth::ApiKey(key),
        });
    }
    None
}

fn xai_signed_in() -> bool {
    xai_oauth::token_path()
        .map(|path| path.exists())
        .unwrap_or(false)
}

fn is_xai_base_url(base_url: &str) -> bool {
    base_url.to_ascii_lowercase().contains("api.x.ai")
}

fn default_model(is_xai: bool) -> String {
    if is_xai {
        DEFAULT_XAI_MODEL.to_string()
    } else {
        DEFAULT_OPENAI_MODEL.to_string()
    }
}

/// Build the JSON body for `POST /images/generations`. Pure helper for tests.
pub(crate) fn build_request_body(
    model: &str,
    prompt: &str,
    n: u32,
    aspect_ratio: Option<&str>,
    resolution: Option<&str>,
    response_format: &str,
) -> Value {
    let mut body = json!({
        "model": model,
        "prompt": prompt,
        "n": n,
        "response_format": response_format,
    });
    if let Some(aspect_ratio) = aspect_ratio.map(str::trim).filter(|s| !s.is_empty()) {
        body["aspect_ratio"] = json!(aspect_ratio);
    }
    if let Some(resolution) = resolution.map(str::trim).filter(|s| !s.is_empty()) {
        body["resolution"] = json!(resolution);
    }
    body
}

/// Parse an OpenAI-compatible generations response into image payloads.
pub(crate) fn parse_generations_response(payload: &Value) -> Result<Vec<GeneratedImage>, String> {
    let data = payload
        .get("data")
        .and_then(Value::as_array)
        .ok_or_else(|| "image generation response missing data[]".to_string())?;
    let mut images = Vec::with_capacity(data.len());
    for (index, item) in data.iter().enumerate() {
        let url = item
            .get("url")
            .and_then(Value::as_str)
            .map(str::to_string)
            .filter(|s| !s.is_empty());
        let b64_json = item
            .get("b64_json")
            .and_then(Value::as_str)
            .map(str::to_string)
            .filter(|s| !s.is_empty());
        if url.is_none() && b64_json.is_none() {
            return Err(format!(
                "image #{index} has neither url nor b64_json in the response"
            ));
        }
        images.push(GeneratedImage { url, b64_json });
    }
    Ok(images)
}

/// POST with one OAuth refresh retry on 401.
async fn post_generations(
    client: &reqwest::Client,
    url: &str,
    endpoint: &ImageEndpoint,
    body: &Value,
) -> anyhow::Result<reqwest::Response> {
    let mut retried = false;
    loop {
        let token = endpoint.bearer().await?;
        let response = client
            .post(url)
            .bearer_auth(token)
            .header(reqwest::header::CONTENT_TYPE, "application/json")
            .json(body)
            .send()
            .await?;
        if response.status() == reqwest::StatusCode::UNAUTHORIZED
            && !retried
            && endpoint.refresh_after_unauthorized().await
        {
            retried = true;
            continue;
        }
        if !response.status().is_success() {
            let status = response.status();
            let text = response.text().await.unwrap_or_default();
            anyhow::bail!("HTTP {status}: {text}");
        }
        return Ok(response);
    }
}

/// Decode b64 or download a URL; returns (bytes, optional source url).
async fn materialize_image(
    client: &reqwest::Client,
    image: &GeneratedImage,
) -> anyhow::Result<(Vec<u8>, Option<String>)> {
    if let Some(b64) = &image.b64_json {
        let bytes = BASE64
            .decode(b64.trim())
            .map_err(|err| anyhow::anyhow!("invalid b64_json: {err}"))?;
        if bytes.len() > MAX_IMAGE_BYTES {
            anyhow::bail!(
                "decoded image is {} bytes (cap is {MAX_IMAGE_BYTES})",
                bytes.len()
            );
        }
        return Ok((bytes, None));
    }
    let url = image
        .url
        .as_deref()
        .ok_or_else(|| anyhow::anyhow!("image has no url or b64_json"))?;
    let bytes = download_image(client, url).await?;
    Ok((bytes, Some(url.to_string())))
}

/// Download image bytes from a temporary generation URL. SSRF-safe: https only,
/// no local/private hosts.
async fn download_image(client: &reqwest::Client, url: &str) -> anyhow::Result<Vec<u8>> {
    let parsed =
        reqwest::Url::parse(url).map_err(|err| anyhow::anyhow!("invalid image url: {err}"))?;
    if parsed.scheme() != "https" {
        anyhow::bail!(
            "refusing to download image over '{}' (only https is allowed)",
            parsed.scheme()
        );
    }
    let host = parsed
        .host_str()
        .ok_or_else(|| anyhow::anyhow!("image url has no host"))?;
    if host_is_blocked(host) {
        anyhow::bail!("refusing to download image from local/private host '{host}'");
    }

    let response = client.get(url).send().await?;
    if !response.status().is_success() {
        let status = response.status();
        anyhow::bail!("image download returned HTTP {status}");
    }
    let mut bytes = Vec::new();
    let mut stream = response.bytes_stream();
    use futures_util::StreamExt;
    while let Some(chunk) = stream.next().await {
        let chunk = chunk?;
        if bytes.len() + chunk.len() > MAX_IMAGE_BYTES {
            anyhow::bail!("image download exceeded {MAX_IMAGE_BYTES} bytes");
        }
        bytes.extend_from_slice(&chunk);
    }
    if bytes.is_empty() {
        anyhow::bail!("image download returned an empty body");
    }
    Ok(bytes)
}

fn host_is_blocked(host: &str) -> bool {
    let host = host.trim_end_matches('.');
    if host.eq_ignore_ascii_case("localhost")
        || (host.len() >= 6 && host[host.len() - 6..].eq_ignore_ascii_case(".local"))
    {
        return true;
    }
    let bare = host.trim_start_matches('[').trim_end_matches(']');
    if let Ok(ip) = bare.parse::<std::net::IpAddr>() {
        return match ip {
            std::net::IpAddr::V4(v4) => {
                v4.is_loopback() || v4.is_private() || v4.is_link_local() || v4.is_unspecified()
            }
            std::net::IpAddr::V6(v6) => {
                if let Some(mapped) = v6.to_ipv4_mapped() {
                    return mapped.is_loopback()
                        || mapped.is_private()
                        || mapped.is_link_local()
                        || mapped.is_unspecified();
                }
                v6.is_loopback()
                    || v6.is_unspecified()
                    || (v6.segments()[0] & 0xfe00) == 0xfc00
                    || (v6.segments()[0] & 0xffc0) == 0xfe80
            }
        };
    }
    false
}

async fn write_image_file(path: &Path, bytes: &[u8]) -> std::io::Result<()> {
    if let Some(parent) = path.parent() {
        tokio::fs::create_dir_all(parent).await?;
    }
    tokio::fs::write(path, bytes).await
}

/// Default path: `generated/<timestamp>-<slug>.png` under the project root.
fn default_output_path(cwd: &Path, prompt: &str) -> PathBuf {
    let stamp = chrono::Local::now().format("%Y%m%d-%H%M%S");
    let slug = slugify_prompt(prompt);
    cwd.join("generated").join(format!("{stamp}-{slug}.png"))
}

/// Filesystem-safe slug from the first few words of the prompt.
fn slugify_prompt(prompt: &str) -> String {
    let mut slug = String::new();
    for ch in prompt.chars() {
        if slug.len() >= 48 {
            break;
        }
        let lower = ch.to_ascii_lowercase();
        if lower.is_ascii_alphanumeric() {
            slug.push(lower);
        } else if (lower.is_whitespace() || lower == '-' || lower == '_')
            && slug.chars().last().is_some_and(|c| c != '-')
        {
            slug.push('-');
        }
    }
    let slug = slug.trim_matches('-').to_string();
    if slug.is_empty() {
        "image".to_string()
    } else {
        slug
    }
}

/// When generating multiple images, append `-1`, `-2`, ... before the extension.
fn output_path_for_index(base: &Path, index: usize, total: usize) -> PathBuf {
    if total <= 1 {
        return base.to_path_buf();
    }
    let stem = base.file_stem().and_then(|s| s.to_str()).unwrap_or("image");
    let ext = base.extension().and_then(|s| s.to_str()).unwrap_or("png");
    let parent = base.parent().unwrap_or_else(|| Path::new(""));
    parent.join(format!("{stem}-{}.{ext}", index + 1))
}

#[cfg(test)]
mod tests {
    use super::*;
    use serde_json::json;

    #[test]
    fn request_body_includes_model_prompt_and_aspect_ratio() {
        let body = build_request_body(
            "grok-imagine-image-quality",
            "a red cube on a table",
            2,
            Some("16:9"),
            Some("2k"),
            "url",
        );
        assert_eq!(body["model"], "grok-imagine-image-quality");
        assert_eq!(body["prompt"], "a red cube on a table");
        assert_eq!(body["n"], 2);
        assert_eq!(body["aspect_ratio"], "16:9");
        assert_eq!(body["resolution"], "2k");
        assert_eq!(body["response_format"], "url");
    }

    #[test]
    fn request_body_omits_empty_optional_fields() {
        let body = build_request_body("dall-e-3", "cat", 1, Some("  "), None, "b64_json");
        assert!(body.get("aspect_ratio").is_none());
        assert!(body.get("resolution").is_none());
        assert_eq!(body["response_format"], "b64_json");
        assert_eq!(body["n"], 1);
    }

    #[test]
    fn parse_url_response() {
        let payload = json!({
            "data": [
                { "url": "https://cdn.example.com/a.png" },
                { "url": "https://cdn.example.com/b.png" }
            ]
        });
        let images = parse_generations_response(&payload).unwrap();
        assert_eq!(images.len(), 2);
        assert_eq!(
            images[0].url.as_deref(),
            Some("https://cdn.example.com/a.png")
        );
        assert!(images[0].b64_json.is_none());
        assert_eq!(
            images[1].url.as_deref(),
            Some("https://cdn.example.com/b.png")
        );
    }

    #[test]
    fn parse_b64_json_response() {
        let payload = json!({
            "data": [ { "b64_json": "aGVsbG8=" } ]
        });
        let images = parse_generations_response(&payload).unwrap();
        assert_eq!(images.len(), 1);
        assert_eq!(images[0].b64_json.as_deref(), Some("aGVsbG8="));
        assert!(images[0].url.is_none());
    }

    #[test]
    fn parse_rejects_empty_item() {
        let payload = json!({ "data": [ { "revised_prompt": "x" } ] });
        let err = parse_generations_response(&payload).unwrap_err();
        assert!(err.contains("neither url nor b64_json"), "{err}");
    }

    #[test]
    fn parse_rejects_missing_data() {
        let err = parse_generations_response(&json!({})).unwrap_err();
        assert!(err.contains("missing data"), "{err}");
    }

    #[test]
    fn slugify_prompt_is_filesystem_safe() {
        assert_eq!(slugify_prompt("A Red Cube!!"), "a-red-cube");
        assert_eq!(slugify_prompt("   "), "image");
        assert_eq!(slugify_prompt("café scene"), "caf-scene");
    }

    #[test]
    fn output_path_for_index_suffixes_when_multiple() {
        let base = PathBuf::from("/tmp/generated/shot.png");
        assert_eq!(
            output_path_for_index(&base, 0, 1),
            PathBuf::from("/tmp/generated/shot.png")
        );
        assert_eq!(
            output_path_for_index(&base, 0, 2),
            PathBuf::from("/tmp/generated/shot-1.png")
        );
        assert_eq!(
            output_path_for_index(&base, 1, 2),
            PathBuf::from("/tmp/generated/shot-2.png")
        );
    }

    #[test]
    fn default_model_depends_on_endpoint() {
        assert_eq!(default_model(true), DEFAULT_XAI_MODEL);
        assert_eq!(default_model(false), DEFAULT_OPENAI_MODEL);
    }

    #[test]
    fn host_is_blocked_for_local_targets() {
        assert!(host_is_blocked("localhost"));
        assert!(host_is_blocked("127.0.0.1"));
        assert!(host_is_blocked("10.0.0.5"));
        assert!(host_is_blocked("192.168.1.1"));
        assert!(!host_is_blocked("cdn.x.ai"));
        assert!(!host_is_blocked(
            "oaidalleapiprodscus.blob.core.windows.net"
        ));
    }

    #[test]
    fn is_xai_base_url_detects_host() {
        assert!(is_xai_base_url("https://api.x.ai/v1"));
        assert!(!is_xai_base_url("https://api.openai.com/v1"));
    }

    #[test]
    fn tool_advertises_generate_image() {
        let tool = GenerateImageTool;
        assert_eq!(tool.name(), "generate_image");
        assert_eq!(tool.access(), ToolAccess::Execute);
        let params = tool.parameters();
        assert_eq!(params["type"], "object");
        assert_eq!(params["required"], json!(["prompt"]));
        assert!(params["properties"]["prompt"].is_object());
        assert!(params["properties"]["aspect_ratio"].is_object());
    }
}
